spring:
  data:
    mongodb:
      uri: mongodb://daetruji:123456@localhost:27027/example_webflux?retryWrites=true&loadBalanced=false&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256



